src/main.py, src/status.py
Add a page to write status in
Fixes #7 
tested local on development platform
=> add status page

requirements.txt, src/forecast.py
- colours for forecast tab
- update dm (for forecast tab)
ran it locally
=> nowcasting_datamodel==1.3.19

src/status.py
fix status by adding id to current status
Fixes #
tested localled
=> add id to status

src/forecast.py
Add option to view GSP
Ran locally
=> Gsp forecast

src/forecast.py
Remove duplicate code
Fixes #36 
ran locally
=> remove duplciate code #36

requirements.txt, src/pvsite_forecast.py
update pvsite_datamodel version
needed to update `requirements.txt` to include `pvsite_datamodel`
saw that there was a problem with the date picker for the `pvsite_forecast`. 
Fixes #41 
ran the code locally and viewed it
=> update to pvsite_datamodel in requirements.txt

requirements.txt
updating pvsite_datamodel
Fixes #41 
checked the text by reading
=> add pvsite-datamodel to requirements

Dockerfile
updating python version so pvsite-datamodel will work.
Fixes #41
changed the Docker file
=> update python version

src/forecast.py
Add `blend` model
tested it locally
=> add blend forecast

src/main.py
Add PVlive intraday to dat after metrics
Fixes #49 
ran locally
=> add plot of pvlive 

src/get_data.py, src/sites_toolbox.py, tests/test_get_data.py
Fixes for adding a site
Fixes #
=> fix for adding to site

src/data/dno.py, src/data/gsp.py
Fix for loading file, when running in docker
- ran locally (not in docker)
- pytest ran locally
- CI tests
=> dynamically get path for gsp and dno

src/get_data.py, src/sites_toolbox.py, tests/test_get_data.py
Add functions and tests to delete a site, a user, and a site group
Fixes #
=> Issue/delete a site, a user, a site group

README.md, src/forecast.py, src/main.py
Option to load `pvnet_gsp_sum`
Helps with https://github.com/openclimatefix/pvnet_app/issues/15
CI tests
=> add optino to show pvnet_gsp_sum

src/main.py, src/plots/utils.py
Fix for colour of  PVNet GSP sum + title fix for RMSE. Fixes #96 #93
=> fix color selection + title bug

src/forecast.py
More checks for probabilistic forecast components
=> checks if forecast includes probabilistic components

src/auth.py
try and except around auth
Helps with #95 
Could not try locally, as error doesnt get raised
=> stop error when running auth

requirements.txt
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
=> nowcasting_datamodel==1.5.32

src/main_india.py
Add india landing page
Fixes #
Ran locally
=> add india page

src/nwp_page.py
Add lon, and lat limites on nwp graph
Fixes #
ran locally on india data
=> Sites filters

src/nwp_page.py
Add default options ofr lat and lon based on nwp data
works on uk and india data
Fixes #
test on uk and india data
=> make more flexible for filtering

src/plots/users.py, src/users.py, tests/plots/test_users.py
Add histrogram of how many API hits per day, for a user
=> add plot for frequency of api hits

requirements.txt
upgrade datamodel to speed up reading users
Fixes #
Ran locally
=> nowcasting_datamodel==1.5.37

src/main.py, src/main_india.py
Edited st.set_page_config() in your main.py and main_india.py to have wider plots. 
Fixes #76 
If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?
=> Update page configuration for Streamlit app

src/pvsite_forecast.py
Show more than 4 days of forecast history
Not tested, but small change
=> 1 year of site foreacsts

src/pvsite_forecast.py
Add a download button, #132 
Note all times are UTC
Fixes #
=> add download button

src/pvsite_forecast.py
Add option to resample data when looking at location forecast
T
=> add option to resample data

src/main_india.py
- add API user page to india
Fixes #
Works for UK
=> add api user page to india

src/pvsite_forecast.py
A few changes made in the code of pvsiteforecast.py that shows the MAE at the bottom of the screen.
Fixes #142 
Ran a few tests on my machine and made changes accordingly to display MAE
- [x ] Yes
- Image of the new webpage displaying MAE
- [ x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x ] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [x ] I have checked my code and corrected any misspellings
=> commit MAE on webpage

src/pvsite_forecast.py
This feature adds the option to view NMAE on the dashboard.
Fixes #
The results have been cross-referenced by manually calculating the numbers
- [x ] Yes
- [ x] Yes
- [ x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [ x] I have checked my code and corrected any misspellings
=> Mae on webpage

requirements.txt
Bump pvsite-datamodel to 1.0.24, 
we need for the change in #156 
Not tested
=> pvsite-datamodel==1.0.24

src/forecast.py, src/plots/utils.py
Add some tweaks to:
- Make extra models be plotted in different colours
- Allow quantiles to be plotted for extra models
- Minor cleaning
Have tested locally to make sure it all runs
=> Add some tweaks

src/users.py
Cache the user requests by 1 minute
Not run locally, but only refactored code
=> cache the last request by user, 1 mins

src/forecast.py, src/main.py, src/plots/forecast_horizon.py, src/plots/pinball_and_exceedance_plots.py, src/plots/utils.py
This pull request primarily for an edge-case bug where too many horizons are selected on the metric page. This causes us to run out of colours in the `line_colour` list. 
This also includes some light tidying and refactoring
=> Tidy and edge case bug

src/forecast.py
@Sukh-P pointed out this should be `.index()` rather than `.get_index()`
Have tested the app locally and it seems to work now
=> Fix list index bug

src/plots/mae_and_rmse.py
Add sub title to main metrics plot
#174 
tested it locally
=> add subtitle

src/forecast.py
Fix for "creation time" on forecast
#178 
Ran it locally
=> fix for gsp_id

src/forecast.py
Fix for elexon plot, so that it shows when for the past too
#183 
Ran it locally
=> fix for elexon plot

requirements.txt, src/users.py
- fix for showing national on api users page
Fixes #
CI tests + ran locally
=> tidy up user page

src/pvsite_forecast.py
Fix for created time
Fixes #
tested locally
=> fix created time, so default to local

requirements.txt
move ot herbie-data not herbie
Fixes #
CI tests
=> install herbie-data

src/nwp_page.py
Update nwp page for india nw
#204 
CI
=> update for nwp india

src/nwp_page.py
Fix NWP india
Fixes #
CI tests
=> fix for nwp india

src/pvsite_forecast.py
Make sure india sites have a time delta of 5.5 hours
CI tests + tried locally
=> make sure timezone differences is 5.5 hours

src/pvsite_forecast.py
Display multiple models on dashboard
#212 
Tested on india local
=> display multiple models for site forecasts

requirements.txt
=> Multi ml mdoels

src/pvsite_forecast.py
Remove un necessary text
CI tests
=> remove st.write

src/pvsite_forecast.py, tests/test_pvsite_location.py
A penalty calculator on dashboard, which tells the total penalty that is incurred in the day.
Fixes #
=> Adds Penalty calculator on dashboard

src/pvsite_forecast.py
Ive put the clipping in the metrics. And left the graph the same
Can now close #198 
CI tests
=> in metrics make sure generation >0

src/pvsite_forecast.py
Dont include inf values in live/gen values
as added site name - #208 
Fixes #
Tested locally
=> dont include inf values + add site name

src/pvsite_forecast.py
add perason correlation
Fixes #
CI tests
=> add person correlation

src/pvsite_forecast.py
Select site by client name
CI tests
=> select site by uuid or client name

src/nwp_page.py
Fix for Metoffice global for NWP data
Check it locally
=> add MO global to india NWP page

requirements.txt, src/sites_toolbox.py, tests/test_sites_toolbox.py
Option to assign ml model to site
Helps with https://github.com/openclimatefix/india-api/issues/100
Tested it locally, assigned a ml model to a site, and saw it was assigned in database and viewing site details
=> add assign ml model to site section

src/pvsite_forecast.py
Fix for uk sites model
Ran it locally
=> Fix uk site model

src/main_india.py, src/mlmodel.py
Add a page to see which site has which model attached to it
Ran it locally
=> Add ml site page

src/mlmodel.py
show the generation datetime for each site, the shows if there is delayed
Ran it locally
=> add last generation to site model

README.md, docker-compose.yml
Docker Compose Setup: A docker-compose.yml file has been added to the project, enabling users to set up and run the application in a Docker container. This simplifies the setup process by automating environment configuration, including optional database connectivity.
Fixes #243  #226
=> [feature] Add Support for Local Installation and Docker Compose Setup

src/nwp_page.py
- tidy up code
- add  "HRES-IFS_india",
- CI tests
- tested localy
=> Nwp update

src/assets/css/status.css, src/status.py, src/utils.py
This PR implements a redesigned and improved update section to address Issue #254 . The previous design was basic and lacked professionalism, impacting the overall user experience. This update introduces a modern layout, better styling, and user-friendly features, aligning with current UI/UX trends. The main changes include:
Fixes #254 
The changes have been tested locally to ensure proper functionality and design adherence. The following steps were performed:
1. Verified that the current status is fetched correctly from the database and displayed in a styled table.
2. Tested the "Update Status" functionality to confirm that new statuses are written to the database successfully.
3. Ensured the layout and styling are responsive and render well across different devices and screen sizes.
4. …
=> feat: New styles for status display

src/mlmodel.py
Add a Frame to change the description of ML Model.
Fixes #247
https://github.com/user-attachments/assets/2bd4c2aa-c026-481a-8079-43134d55d691
=> Add a Frame to change and update the description of ML Models

src/main.py, src/satellite_forecast.py
Add a satellite forecast page
- Ran it locally
=> Satellite forecast

requirements.txt
This add ML description to MLModel.SQL
Ci tests
=> pvsite-datamodel==1.0.50

src/satellite_forecast.py
Recently the 15 minutely satellite was deleted from s3 for being to old. This meant the cloudcasting page of the dashboard was crashing since it assumed both the 5 and 15 minute satellite would be available even if one of them was very out of date.
This PR fixes this expectation and allows the cloudcasting page to work if at least one of the satellite sources is available
=> Fix for unavailbale sat sources

src/pvsite_forecast.py
This feature adds the visualisation of the errors throughout the selected time period of the site.
Tested Locally.
=> Visualisation of the errors

src/nwp_page.py
- Add NWP NL
- get time series plot wokring
- add different tick box
=> add ECMWF NL and get Time series plot wokring

src/main.py, src/plots/pinball_and_exceedance_plots.py
Add summary stats for pinball and exceedence stats
=> add pinball and exceedence summary stats

src/users.py
In the api suer tab, load national by default, not sites
=> load national first, not sites

requirements.txt
Upgrade dm
#301 
- CI test
- tested locally
-
=> pvsite-datamodel==1.1.2

requirements.txt, src/get_data.py, src/main.py, src/mlmodel.py, src/pvsite_forecast.py, src/site_toolbox/get_details.py, src/site_toolbox/site_group_management.py, src/sites_toolbox.py, src/users.py, tests/test_sites_toolbox.py
Update to dm 1.2
ran unit tests,
not able to run against local database until migration. Tricky to test
=> updates dm 1.2

src/pvsite_forecast.py, src/sites_toolbox.py
=> update site toolbox

src/mlmodel.py
=> site --> client_location_name

src/main.py, src/main_india.py
I made a main navigation page. This when it first loads it not on the slow Metrics page, and we can add some documentation on this page too. 
UK
India
ran locally
=> Title page

src/main.py
Small change to update menu text on home page
Fixes #
=> Update menu text on home page

src/pvsite_forecast.py
Only use one database sessions
No new code, just reduced the number of sessions
-  [x] CI tests
=> only use one db connection

requirements.txt, src/pvsite_forecast.py
- speed up model read, for pvsite forecast
Ci test
=> speed up model read

requirements.txt, src/pvsite_forecast.py
Sped up reading NL results. This does this using new fv function
#298 
CI tests
=> speed up reading site forecast

requirements.txt, src/pvsite_forecast.py
Speed up data read
- CI tests
- ran locally
=> get da forecast read

src/satellite_page.py
Add option -o when unzipping satellite data
- ran it locally
=> override when unzipping satellite data

.github/workflows/branch_ci.yml
disabling linting as requested by @peterdudfield in PR #356
=> Disable linting

requirements.txt, src/cloudcasting_page.py, src/data_paths.py, src/forecast.py, src/get_data.py, src/main.py, src/main_india.py, src/mlmodel.py, src/nwp_page.py, src/plots/users.py, src/plots/utils.py, src/pvsite_forecast.py, src/satellite_page.py, src/site_toolbox/get_details.py, src/users.py, src/utils.py
- Move the data paths to a shared file
- Remove unused imports in various places
- Remove dead portion of a function
- Remove ocf_blosc2
- Rename satellite forecast page
=> Minor clean and fix

.github/workflows/branch_ci.yml, .github/workflows/main_ci.yml
- copy github work over and add streamlit secret
Helps with #356 
- CI tests, and check it by deploying it to dev
=> copy over workflow, and pust streamlit secret

src/pvsite_forecast.py
Allow the site foreacst to look back 2years
- CI tests
- its a small change so shuold be ok to deploy straight to dev
=> Update start date range to two years
