src/auth.py
Currently defaults to `new-password` which suggests creating a password through 1Password etc.
It has not, and may fail linting, who knows
=> Add autocomplete to allow 1Pass to fill field

src/main.py
add common y limit for MAE graphs, this makes it easier to compare different models
Fixes #
ran locally
=> add MAE limits (so models can be comapred)

src/main.py
Add table to show averaged results per forecast horizon
This will be useful to compare Pnvet 2.0 with the other models
ran it locally
=> add table showing averaged values

requirements.txt, src/forecast.py, src/main.py
This adds code to `main.py`, the `metric page`, to display `Daily Lates MAE All GSPs`. 
Currently the data frame I created for displaying `Daily Latest MAE All GSPs` returns an empty array, so I'd be curious to have answers to the following: 
- how best to query the database in cases like this to see if there is the data for `Daily Latest MAE All GSPs`
-  why the data frame I've added on `line 180` of `main.py`, `df_mae_all_gsp`, is empty
I tried the following in the pgAdmin database to see if the data's there:
`select * from metric_value 
where created_utc >='2023-06-28'
and metric_id = 2`
and did see values in the `value` column: 
Theoretically the new line would be in the following graph, `fig6` in `main.py`:
Fixes #29
=> add line for Daily Latest MAE all GSPs to fig6

src/forecast.py
There is the following error when `National_xg` was selected in `forecast_models` and the `gsp_id` was not for the `National forecast`:
This PR adds a warning and the chart still loads even if the user has selected a regional `GSP`:
Ran the code locally.
=> fix error when National_xg selected for a GSP

requirements.txt
pvsite-datamodel needs pandas version >= 1.5.3, so i've increased the version 
Fixes #41
updated the requirements.txt for pandas version 1.5.3
=> change pandas version so pvsite-datamodel works

src/forecast.py, src/main.py
- fix for probablistc
- updated default time for forecast
- make pvnet default
fixes #90 fixes #91
Ran it locally
=> bug fixes on forecast

requirements.txt, src/main.py, src/plots/users.py, src/users.py, tests/plots/test_users.py
Add user page. Can see
- when each user last used the api
- timeline of the api usage for each user
Fixes #39 
- tested it locally
- added a plot test
=> add user api page

src/forecast.py, src/plots/utils.py
Add options to see multiple creation times
Fixes #
Ran it locally
=> add multi creation times which fade out

requirements.txt, src/main.py, src/nwp_page.py
Add a page where NWP data can be explored
=> add nwp viewing page

requirements.txt, src/pvsite_forecast.py
add filter on side of site forecast page
=> add options of forecast page

src/forecast.py
- add more init times on forecast
tested locally
=> add more init times

requirements.txt, src/users.py
#143 
Add optiont to view sites API requests. This will work for India too
The user can select which database they want to look at
Fixes #
Ran it locally
=> add option to see sites database api requests.

src/pvsite_forecast.py
Code changes adds an end date to the forecast + name on the webpage
These changes are to the #154 #153 
=> End date + NMAE by capacity

src/adjuster.py, src/main.py
Add a page to display the adjuster values
Tried it locally and it works
=> add adjuster page

src/forecast.py, src/plots/utils.py
This pull request makes the colours of lines which are not explicitly given a colour (i.e. the extra models) more consistent in the app and this easier to analyse. Also adds a fix to make the uncertainty lines disappear when the central line is deselected in the key
=> Make colours more consistent

src/plots/utils.py
Currently all PVNet models start with either `pvnet_v2_*` or `pvnet_day_ahead_*` this change means that the probabilistic and regional plot features will be available for the pvnet_day_ahead model outputs.  
No additional tests added
=> Include all PVNet models in plot features

src/forecast.py
A previous commit (my bad) broke switched the line styles so that the initial estimate was shown with a solid line and the updated estimate was a dashed line. This reverses the change to what it should be.
=> Fix PVLive line styles

requirements.txt, src/forecast.py, src/plots/elexon_plots.py, tests/test_elexon_plot.py
This pull request makes two updates. First, it adds the `elexonpy` library to the requirements. Second, it adds a feature to show forecasts for three types of processes: Day Ahead, Intraday Process, and Intraday Total. 
PFA the screenshot of the forecast page : 
Fixes #172
=> Add elexonpy to requirements and display forecasts for different process types

src/plots/elexon_plots.py
This pull request updates the `add_elexon_plot` function to set the initial visibility of specific forecast traces in the Plotly figure. The "Intraday Process" and "Intraday Total" forecasts will now be hidden by default when the page first loads, but will still be included in the legend.
PFA the screenshot : 
Fixes #180
=> Hide Intraday Forecasts Initially in Plotly Figure

src/forecast.py
This PR modifies the `forecast_page()` function to conditionally display the Elexon plot only when the "National" region is selected. 
Fixes #183
=> Add conditional display of elexon plot for national region in forecast page

src/pvsite_forecast.py
Fix, if no forecast data, but there is generation
Tested in locally
=> fix for no forecast date

.gitignore, src/pvsite_forecast.py, tests/test_pvsite_location.py
The following changes in the code makes sure that we are tracking site wise penalty calculations, as each site/state/generation type has different penalty bands
The code has been ran locally to see if it works
=> site wise penalty

src/plots/forecast_horizon.py
This PR resolves the issue of renaming "Daily Total MAE" to "Latest Forecast" in the MAE by Horizon plot as described in issue #193 .  The changes ensure consistent terminology and improve clarity in the plot labels.
Fixes #193 
Run it locally
The changes were tested to ensure functionality and consistency.  
You can reproduce the changes by opening the file located at `src\plots\forecast_horizon.py` and inspecting line number 27. When you create the `forecast_horizon` chart, you will see the updated label, "Latest Forecast," displayed correctly.
=> Rename MAE plot line from "Daily Total MAE" to "Latest Forecast"

src/mlmodel.py
This fix adds map on the dashboard, for the user to see if the actual location of the sites,
Fixes #
=> Update to add map on the dashboard

.github/workflows/pytest.yml
This update modifies the GitHub Actions workflow to trigger `pytest.yml` CI tests on external pull requests (PRs). The workflow is now set to run tests on PR creation, updates, reopening, and when marked as "ready for review".
Fix #251
=> Added CI Tests for External PRs

src/site_toolbox/get_details.py, src/sites_toolbox.py, tests/test_sites_toolbox.py
This PR adds an option to include `county` and `asset type` when adding sites in the tool. The new fields are incorporated into the display object and the tool's functionality is updated accordingly.
Fixes #224 
The following tests were performed to verify the changes:
- Added unit tests to ensure the new fields are correctly added to the display object.
- Manually tested the functionality by adding sites with `county` and `asset type` fields.
- Conducted a quick sanity check to validate the data processing for the new fields.
https://github.com/user-attachments/assets/01dd3a58-0d18-49e5-8607-7183b1ef6314
=> feat: Add country and asset type inputs to sites toolbox page

src/main_india.py, src/weather_graph.py
The following page adds a weather data page to dashboards to get historical or forecast temperature and wind speed data on the dashboard
=> Adds a weather data page on the dashboard

src/pvsite_forecast.py, src/utils.py
=> Change Zoneinfo to pytz module

src/plots/users.py, src/users.py
The following update to the code will display the progression of sites allocated per users over time.
This Pr is in correspondence to the issue: https://github.com/openclimatefix/analysis-dashboard/issues/260
The code has been tested locally
=> addition of new sites will be displayed on dashboard

requirements.txt
Fix for numcodecs==0.15.1, to get nwp visulization working
Ci test
=> add numcodecs==0.15.1

src/users.py
This PR reduces the API use usage initial load from 31 days down to 7 days. 
Fixes #
The analysis dashboard has been repeatedly crashing recently on the API user page. This should reduce the amount of data originally loaded.
This has not been tested locally, but it is a very small change that is not to anything critical for the app. 
=> Load a week of API users

src/plots/elexon_plots.py
This PR hides all Elexon forecasts ("Day Ahead", "Intraday Process", and "Intraday Total") by default on the forecast page.
Currently, only "Intraday" forecasts were hidden by default (`legendonly`), while "Day Ahead" remained visible. This PR ensures **all** Elexon forecast traces are hidden on initial load to reduce visual clutter, and can be toggled via the legend.
Fixes: [#313 ]
Ran `streamlit run` locally and verified all Elexon forecasts appear in the legend but are hidden by default.
=> Hide all Elexon forecasts by default on forecast page

src/users.py
Only show plot of sites on API sites page, not the National
CI tests
=> only show cumulativ sites plot if sites selected

src/plots/elexon_plots.py, src/pvsite_forecast.py, tests/test_elexon_plot.py
Replaced deprecated or inconsistent pandas frequency strings ('15T', '30T') with '15min' and '30min' across code and tests for clarity and future compatibility.
Fixes #334
=> Standardize time frequency strings to '15min' and '30min'

requirements.txt
Changed the torch library line in the `requirements.txt` file to download CPU-only torch.
Fixes #332
I created a new virtual environment using `python -m venv myenv`, then ran the `pip install -r requirements.txt` command to install the dependencies and checked with the `pip list` command to see that only torch CPU was installed for torch.
=> Changed the requirements.txt to install CPU-only torch.
